version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo "Install dependencies"

  build:
    commands:
      - echo "Build started on `date`"
      - docker build -t $DOCKER_IMAGE:latest . --platform=linux/amd64
      - docker push $DOCKER_IMAGE:latest
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Post build started on `date`"
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $DOCKER_IMAGE:latest
      - echo "Post build completed on `date`"